# Generated by Django 4.2.5 on 2023-10-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Classic', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('duration', models.IntegerField(default=30)),
            ],
        ),
    ]
