# Generated by Django 4.2.5 on 2023-11-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_transaction_payment_id_transaction_expires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment',
            new_name='payment_user_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
    ]
