# Generated by Django 4.2.5 on 2023-11-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_payment_transaction_payment_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_user_id',
        ),
    ]
