# Generated by Django 4.2.5 on 2023-11-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_transaction_payment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expires',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Payment ID'),
        ),
    ]
