# Generated by Django 4.2.5 on 2023-11-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_transaction_expires_transaction_payment_instacne_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_instacne_id',
            new_name='payment_instance',
        ),
    ]
