# Generated by Django 4.2.5 on 2023-10-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_requests_delete_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
