# Generated by Django 4.2.5 on 2023-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_is_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('about_me', models.TextField()),
                ('teaching_style', models.TextField()),
                ('work_experience', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
