# Generated by Django 4.2.5 on 2023-10-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_tutorapplication_alter_user_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorApplication',
        ),
    ]
