# Generated by Django 4.2.5 on 2023-10-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
