# Generated by Django 4.2.5 on 2023-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_tutorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplication',
            name='email',
        ),
    ]
