# Generated by Django 4.2.5 on 2023-11-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
