# Generated by Django 4.2.5 on 2023-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_tutorapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='phone',
            field=models.CharField(),
        ),
    ]
