# Generated by Django 4.2.5 on 2023-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_user_is_trainer_alter_tutorapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Tvip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
