# Generated by Django 4.2.5 on 2023-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_rating_user_alter_rating_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
