# Generated by Django 4.2.5 on 2023-11-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_tutorapplication_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(default='India', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
