# Generated by Django 4.2.5 on 2023-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_tutorapplication_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
