# Generated by Django 4.2.5 on 2023-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_alter_tutorapplication_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=200, null=True),
        ),
    ]
