# Generated by Django 4.2.5 on 2023-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_alter_tutorapplication_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
