# Generated by Django 4.2.5 on 2023-11-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_alter_tutorapplication_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplication',
            name='country',
        ),
    ]
