# Generated by Django 4.2.5 on 2023-11-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_remove_tutorapplication_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorapplication',
            name='name',
        ),
    ]
