# Generated by Django 4.2.5 on 2023-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_remove_tutorapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
