# Generated by Django 4.2.5 on 2023-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_tutorapplication_country_tutorapplication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
